name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      [master]
    types:
      [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: '16'

      - name: install dependencies
        run: npm install 

      - name: linter
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: npm test

      - name: e2e tests
        uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a
        with:
          command: npm run e2e
          start: npm run start
          wait-on: http://localhost:8000

      - name: Trigger Deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch